apiVersion: v2
name: aws-pod-identity-webhook
description: This webhook is for mutating pods that will require AWS IAM access.
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
home: https://github.com/giantswarm/aws-pod-identity-webhook
sources:
  - https://github.com/aws/amazon-eks-pod-identity-webhook
version: 2.1.0
appVersion: 0.6.7
annotations:
  io.giantswarm.application.team: "phoenix"
  config.giantswarm.io/version: 1.x.x
